### ISSUE TITLE
multi account

### ISSUE THREAD

**Issue by khag7** [Tr4sHCr4fT/fastmap#1]
i'm very impressed by everything you have posted on reddit. I think you have the clearest understanding of how to make these scans efficient. Your database is structured beautifully.

I'm not skilled in python. Could you copy some features from TBTerra's spawnScan and spawnTracker repos (they also use tejado's api) or pokeminer? Namely multi account. I'd love to just drop into the config file something like "base_username:kevin, total_accts:200, password:mypass123" and it would use kevin1 thru kevin200 with the same password. I'd like to define a rectangular area with NW and SE coords. Then we just scan and fill the db with spawn points very very quickly.

**Comment by tcmaps** [comment]
sadly, i don't have any threading concept yet, which we would need for multiple accounts  
feel free to fork & pr ;)  
for the sw/ne coordinates, just edit the two lines in utils.py where it gets edge coords from geodlib

**Comment by tcmaps** [comment]
added in 1.5
