### ISSUE TITLE
Cannot launch yet.

### ISSUE THREAD

**Issue by SeeingBlue** [Tr4sHCr4fT/fastmap#2]
Some errors
http://pastebin.com/dMD8dE38
Am I doing something wrong?

**Comment by Tr4sHCr4fT** [comment]
reworked stuff, mind trying again?

**Comment by tcmaps** [comment]
should be fixed now, works with your location at least

**Comment by tcmaps** [comment]
definitely fixed now (by switching from uint64 cell id's to hex encoding / tokens)
